name: CI (main)
on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml

  deploy:
    name: Deploy to Apify
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apify/push-actor-action@v1
        with:
          token: ${{ secrets.APIFY_TOKEN }}
